/**
 * Generated by scripts/wire-book-products.mjs from .ghl-book-products.json.
 * Do not edit by hand — re-run the wire script after re-seeding GHL.
 *
 * The BooksSection on the homepage imports BOOK_CHECKOUTS to turn each
 * book cover into a working checkout link. Until the seed + wire scripts
 * have been run with real GHL credentials, this map stays empty and the
 * BooksSection falls back to the placeholder "Learn More" CTA.
 */

export type BookCheckout = {
  /** Slug shared with BOOKS in portfolio-data.ts. */
  slug: string;
  /** Display title (kept here for sanity / cross-checking). */
  title: string;
  /** USD list price as set in GHL. */
  price: number;
  /** GHL product id — useful for analytics or follow-up automations. */
  productId: string;
  /** GHL price id. */
  priceId: string;
  /** Public checkout / pre-order URL the buyer opens. */
  url: string;
};

export const BOOK_CHECKOUTS: Record<string, BookCheckout> = {};
